### ISSUE TITLE
Duplicate token OP-RIGHT-BRACE

### ISSUE THREAD

**Issue by AshesITR** [r-lib/xmlparsedata#11]
https://github.com/r-lib/xmlparsedata/blob/6474f795ac8e480779aca10a298b1a32f8ec75dc/R/package.R#L167

It seems like that is a typo and should read `OP-RIGHT-BRACKET`.

**Comment by gaborcsardi** [comment]
Right! Good catch. Would you like to submit a pull request?

**Comment by AshesITR** [comment]
Sure
