### ISSUE TITLE
Inverse function in scope?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/xmlparsedata#16]
Is it in scope for this package to have something like `utils::getParseText` that goes from the XML parse tree either straight back to file, or back to a `utils::getParseData` `data.frame` which can then be given to `utils::getParseText`?

**Comment by gaborcsardi** [comment]
IDK. Can I ask your use case? 

I guess manipulating the XML and then writing out the file would be cool.

**Comment by MichaelChirico** [comment]
I am thinking of whether it would be possible to write a styler that feels basically like `lintr` internals-wise -- instead of just identifying issues with xpath conditions, we can identify them, then fix them on the parse tree. There are other ways to accomplish this but if a lot of the logic can be kept on the XML version it would make the logic more central.

**Comment by gaborcsardi** [comment]
Yeah, that would be quite cool. In theory there is XSLT to transform XML. But in practice, most people find both XPath and XSLT hard to work with.

**Comment by gaborcsardi** [comment]
PR's are welcome. :) I guess the difficulty is to work out what to do with the line and column numbers when you do the transformation or the conversion.

**Comment by gaborcsardi** [comment]
I am closing this, but feel free to reopen if you want to discuss it more.
