### ISSUE TITLE
Form feed (\f = rawToChar(as.raw(0x0c))) produces invalid XML?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/xmlparsedata#19]
I was parsing some R source code and ran into this:

https://github.com/wch/r-source/blob/e7eb333dd43be7f7e5ce12d1c31d1934c6b79ac9/tests/reg-packages.R#L232

MRE:

```
xml <- xmlparsedata::xml_parse_data(parse(text = "cat('\f')\n"))
cat(xml)
# <exprlist>
# <expr line1="1" col1="1" line2="1" col2="8" start="10" end="17">
# <expr line1="1" col1="1" line2="1" col2="3" start="10" end="12">
# <SYMBOL_FUNCTION_CALL line1="1" col1="1" line2="1" col2="3" start="10" end="12">cat</SYMBOL_FUNCTION_CALL>
# </expr>
# <OP-LEFT-PAREN line1="1" col1="4" line2="1" col2="4" start="13" end="13">(</OP-LEFT-PAREN>
# <expr line1="1" col1="5" line2="1" col2="7" start="14" end="16">
# <STR_CONST line1="1" col1="5" line2="1" col2="7" start="14" end="16">'
#                                                                       '</STR_CONST>
# </expr>
# <OP-RIGHT-PAREN line1="1" col1="8" line2="1" col2="8" start="17" end="17">)</OP-RIGHT-PAREN>
# </expr>
# </exprlist>

xml2::read_xml(xml)
# Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  : 
#   PCDATA invalid Char value 12 [9]
```

I'm not sure if this is an `xmlparsedata` issue or a `read_xml` one, but starting here. FWIW this site lists the HTML equivalent as `&#12;`; that said, a direct fix doesn't seem to solve the issue:

```
xml <- gsub("\f", "&#12;", xml, fixed = TRUE)
xml2::read_xml(xml)
# Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  : 
#   xmlParseCharRef: invalid xmlChar value 12 [9]
```

[This Q&A](https://stackoverflow.com/a/19633698/3576984) suggests there's no simple way to deal with the issue... and looking at how `\n` is dealt with, it's less clear `xmlparsedata` should be doing something here...

`\v` has the same issue, at a glance, as I'm sure a few other weird characters from the ASCII table do as well...

**Comment by gaborcsardi** [comment]
Yeah, this is a tough one. You cannot have these control characters in XML 1.0. We could simply replace them with another character, e.g. a `\t` or a space. IDK if xmlparsedata should do this automatically, probably yes? Maybe with a warning?

**Comment by gaborcsardi** [comment]
Unfortunately we cannot replace them with the escaped form, because that's two (or more) characters, which messes up the positions within the file.

Btw. we could also submit a patch to R to replace the actual embedded control character with the escape sequence `\f`:
```r
❯ capture.output(eval(parse(text = 'cat("foo\fbar\n")')))
[1] "foo\fbar"

❯ capture.output(eval(parse(text = 'cat("foo\\fbar\\n")')))
[1] "foo\fbar"
```

`R CMD check` does not seem to check for control characters, so there are probably some packages that have them.

**Comment by MichaelChirico** [comment]
>  We could simply replace them with another character

With an eye to invertibility my instinct is not to do that (unless there are other cases where a non-invertible kludge is applied already?)... a warning does sound good.

> we could also submit a patch to R to replace the actual embedded control character with the escape sequence \f

Oh, nice catch! I do think that's a good fix for this case. Seems good to have this written more evidently in the R source as well.

**Comment by gaborcsardi** [comment]
> With an eye to invertibility my instinct is not to do that (unless there are other cases where a non-invertible kludge is applied already?)

Maybe we could replace with the escaped form, but keep the column numbers the same. But this is messy as well, because the string lengths will not match the file positions.

Yet another hack would be to have some additional data that stores these replacements.

But I am not sure that this (hopefully) rare issue is worth the complications, TBH.

**Comment by MichaelChirico** [comment]
> I am not sure that this (hopefully) rare issue is worth the complications, TBH.

me neither, which is why it'd ~probably be fine to just warn IMO... we can gsub both the input and the output of xml_parse_data to do with the character as we see fit, right?

between warning and just documenting (no warning), I would lean towards warning BTW

**Comment by gaborcsardi** [comment]
OK, that makes sense. It should be fast and simple, except that we need to worry about encodings a bit I am afraid.

**Comment by MichaelChirico** [comment]
grepl with useBytes won't cut it?

**Comment by gaborcsardi** [comment]
> grepl with useBytes won't cut it?

Maybe it will, but I don't know much about the CJK encodings? Are they still used? Can they have false positives? 

Otherwise for latin1 and UTF-8 it is easy.

**Comment by MichaelChirico** [comment]
I thought ASCII range is shared by all encodings, I hope that assumption is
correct 😅

I do see this however https://stackoverflow.com/a/1775218/3576984

but this answer is more useful: https://stackoverflow.com/q/19680460/3576984

**Comment by MichaelChirico** [comment]
I've always read this from ?Encoding as supporting my assumption:

> ASCII strings will never be marked with a declared encoding, since their representation is the same in all supported encodings.

but it's not clear if "supported" means "supported by Encoding(), i.e. just latin-1 or UTF-8", or "supported by R in general"

**Comment by gaborcsardi** [comment]
The question is, are you sure that in CJK a surrogate byte cannot be `0c` etc. ?

**Comment by gaborcsardi** [comment]
Seems to be true for Big5: https://en.wikipedia.org/wiki/Big5

**Comment by gaborcsardi** [comment]
I guess we can assume that the `0x00`-`0x1F` control bytes will not be part of any multi-byte character, so then it is easy.

**Comment by gaborcsardi** [comment]
https://developer.r-project.org/Encodings_and_R.html

>Encodings which are likely to cause problems include
> 
>Vietnamese (VISCII). This uses 186 characters including the control characters 0x02, 0x05, 0x06, 0x14, 0x19, 0x1e: the Windows GUI makes use of these as control characters.
Big5, GBK, Shift-JIS. These are all 1- or 2-byte encodings including ASCII as 1-byte chars (except Shift-JIS replaces backspace by ¥) but whose second byte overlaps the ASCII range.

AFAICT the Big5 does not overlap with control characters, and we can probably ignore VISCII.

**Comment by gaborcsardi** [comment]
@MichaelChirico Seems like we are already dropping some control characters:
https://github.com/r-lib/xmlparsedata/blob/88b6e62fb414de33867bb22960abdb57860860f0/R/package.R#L179-L182

So should we drop the rest?

**Comment by MichaelChirico** [comment]
Ah indeed. Yes that's the simplest solution

**Comment by gaborcsardi** [comment]
I replaced the three `gsub()` calls with one, and this is now actually marginally faster, so all is good. :) Let me know if you have any issues. Otherwise I'll make a new release.

**Comment by MichaelChirico** [comment]
Looks great (and glad this spurred on using one `gsub` call 😎)! Thanks!
