### ISSUE TITLE
Missing documentation of start/end metadata

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/xmlparsedata#34]
I am trying to understand what these values mean, as it's apparently not something simple -- I had thought it's "character number in file" but I'm seeing `start` bigger than the file size.

```r
str <- "length(
  foo(
    x, y, z
  ) ==
  bar(
    a, b, c
  )
)"
writeLines(str, tmp <- tempfile())
nodes = parse(tmp) |>
  xmlparsedata::xml_parse_data() |>
  xml2::read_xml() |>
  xml_find_all("//*")
summary(as.integer(xml_attr(nodes, "start")))
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
#   13.00   30.00   47.00   52.39   77.00   97.00       1 
summary(as.integer(xml_attr(nodes, "end")))
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
#   18.00   42.00   54.00   58.79   80.00   97.00       1 
file.size(tmp)
# [1] 59
```

`?xml_parse_data` doesn't mention these at all

**Comment by MichaelChirico** [comment]
From here, it looks like the idea is to first "rectangle" the file, then use "character number in pseudo-file"? Any particular reason for that (just easier to calculate maybe?)?

https://github.com/r-lib/xmlparsedata/blob/45960fb744102c03338c8ae59e01de90b79e87e8/R/package.R#L103-L105

I'm asking b/c it looks currently impossible to use `start`/`end` for this use case:

https://github.com/r-lib/lintr/pull/2124#discussion_r1320381132

Because the current "local" `source_expression` has no way of "knowing" the _global_ file "rectangle size", I have no way (AFAICT) to e.g. use offsets to pull out the relative positions & `substr()` the file.

**Comment by MichaelChirico** [comment]
Hmm, I guess this field is also not correct in general, though I don't think there's anything we can do about it:

```r
str <- '
"
abcdefghijklmnopqrstuvwxyz
"
1 + 1
'
writeLines(str, tmp <- tempfile())

parse(tmp) |>
  xmlparsedata::xml_parse_data() |>
  xml2::read_xml() |>
  as.character() |>
  writeLines()
```

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<exprlist>
  <expr line1="2" col1="1" line2="4" col2="1" start="13" end="25">
    <STR_CONST line1="2" col1="1" line2="4" col2="1" start="13" end="25">"
abcdefghijklmnopqrstuvwxyz
"</STR_CONST>
  </expr>
  <expr line1="5" col1="1" line2="5" col2="5" start="31" end="35">
    <expr line1="5" col1="1" line2="5" col2="1" start="31" end="31">
      <NUM_CONST line1="5" col1="1" line2="5" col2="1" start="31" end="31">1</NUM_CONST>
    </expr>
    <OP-PLUS line1="5" col1="3" line2="5" col2="3" start="33" end="33">+</OP-PLUS>
    <expr line1="5" col1="5" line2="5" col2="5" start="35" end="35">
      <NUM_CONST line1="5" col1="5" line2="5" col2="5" start="35" end="35">1</NUM_CONST>
    </expr>
  </expr>
</exprlist>
```

Note that `start = "13"` and `end = "25"` for the `STR_CONST` containing the alphabet...

**Comment by gaborcsardi** [comment]
These attributes are merely for ordering AFAICT from the source code, and you cannot use their actual values. 

It would be great to have "file position", I have some vague memories that this info is lost in the parser, but I can't remember the details.
