### ISSUE TITLE
Error on empty expression

### ISSUE THREAD

**Issue by renkun-ken** [r-lib/xmlparsedata#8]
```r
xmlparsedata::xml_parse_data(expression())
```

```
Error in !nrow(pd) : invalid argument type
```

**Comment by gaborcsardi** [comment]
x: an expression returned from ‘parse’, or a function or other
          object with source reference information

`expression()` does not have source references:
```r
❯ getParseData(expression())
NULL
```

**Comment by renkun-ken** [comment]
Thanks! Just noticed that it is caused by `parse(text = character(0))` returning `expression()` without source references. Should replace `character(0)` with `""` instead.

Should be fixed on my side.
